# Generated by Django 6.0.3 on 2026-03-31 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("timeout", "Timeout"),
                            ("error", "Error"),
                            ("unexpected_status", "Unexpected Status"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, default=200, null=True),
                ),
                ("response_time_ms", models.PositiveIntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.service",
                    ),
                ),
            ],
            options={
                "db_table": "health_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "-checked_at"],
                        name="health_chec_service_a0a4a8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UptimeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("total_checks", models.PositiveIntegerField(default=0)),
                ("successful_checks", models.PositiveIntegerField(default=0)),
                (
                    "avg_response_time_ms",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "min_response_time_ms",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "max_response_time_ms",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.service",
                    ),
                ),
            ],
            options={
                "db_table": "uptime_records",
                "ordering": ["-hour"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "hour"), name="unique_service_hour"
                    )
                ],
            },
        ),
    ]
